import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/page";
import toast, { Toaster } from "react-hot-toast";
import CartContextProvider from "@/components/context/CartContext";
import WishListContextProvider from "@/components/context/WishListContext";
import MySessionProvider from "@/components/MySessionProvider/MySessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MySessionProvider>
        <CartContextProvider>
       <WishListContextProvider>
          <Navbar />
          <div className="container mx-auto py-5">
            {children}
            <Toaster />
          </div>
        </WishListContextProvider>
        </CartContextProvider>
        </MySessionProvider>

      </body>
    </html>
  );
}
